/*
 * This source file was generated by the Gradle 'init' task
 */
package aeroplanecost;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    
}
