/*
 * This source file was generated by the Gradle 'init' task
 */
package aeroplanecost;

import java.util.*;

import aeroplanecost.Client.Client;
import aeroplanecost.Plane_Commands.PlanesStartUp;
import aeroplanecost.Plane_Commands.TypePlanes;

public class Main {

    // Creating an ArrayList to store Airplane objects
    static ArrayList<TypePlanes> airplanes = new ArrayList<>();

    public static void main(String[] args) {
        PlanesStartUp.launchWelcomeMenu();
        Client.captureClient();
        Scanner input = new Scanner(System.in);
        System.out.println("Enter (1) to launch menu or any other key to exit");
        int menuLaunch = input.nextInt();

        if (!(menuLaunch == 1)) {
            System.out.println("Fairwell Aviator");
        } else {
            int operaterChoice;
            do {
                operaterChoice = PlanesStartUp.launchSelectionMenu();
                if (operaterChoice == 1) {

                    // Adding different types of Airplane objects to the ArrayList
                    airplanes.add(new TypePlanes("Boeing 737", "Boeing", 188, 876, "Turbofan", 100000000));
                    airplanes.add(new TypePlanes("Airbus A320", "Airbus", 150, 871, "Turbofan", 98000000));
                    airplanes.add(new TypePlanes("Cessna 172", "Cessna", 4, 226, "Piston", 275000));
                    airplanes.add(new TypePlanes("Lockheed C-130 Hercules", "Lockheed Martin", 92, 671, "Turboprop",
                            30000000));
                    airplanes.add(
                            new TypePlanes("Gulfstream G650", "Gulfstream Aerospace", 18, 982, "Turbofan", 65000000));
                    airplanes.add(new TypePlanes("Antonov An-225 Mriya", "Antonov", 6, 850, "Turbofan", 300000000));
                    airplanes.add(new TypePlanes("F-22 Raptor", "Lockheed Martin", 1, 2410, "Jet", 150000000));
                    airplanes.add(new TypePlanes("Boeing 747-8", "Boeing", 467, 988, "Turbofan", 420000000));
                    airplanes.add(new TypePlanes("Airbus A380", "Airbus", 853, 1020, "Turbofan", 445000000));
                    airplanes.add(new TypePlanes("Embraer E195-E2", "Embraer", 146, 871, "Turbofan", 60000000));

                    // Calling displayReports for all airplanes
                    TypePlanes.displayAllReports(airplanes);
                } else if (operaterChoice == 2) {
                    // Add a Banker reference
                    Client.captureBanker();
                } else if (operaterChoice == 3) {
                    // Delete a Banker Reference
                    Client.DeleteBanker();

                } else if (operaterChoice == 4) {
                    // Exit application
                    Client.printClient();
                    PlanesStartUp.exitPlaneApplication();
                }
            } while (operaterChoice != 4);
        }
    }

}
