/*
 * This source file was generated by the Gradle 'init' task
 */
package prog6112_a1_v1;

import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        System.out.println("STUDENT MANAGEMENT APPLICATION" + "\n********************************************");
        System.out.println("Enter (1) to launch menu or any other key to exit");
        int menuStart = input.nextInt();
        
        if (!(menuStart == 1)) {
            System.out.println("Have a good day :)");
        }else{
            int userChoice;
            do {
                userChoice = Student.launchMenu();
                if (userChoice == 1) {
                    Student.captureStudent();
                } else if (userChoice == 2) {
                    // Search Student
                    Student.captureID();
                } else if (userChoice == 3) {
                    // Delete a student
                    Student.DeleteStudent();
                } else if (userChoice == 4) {
                    // Print Student Report
                    Student.StudentReport();
                } else if (userChoice == 5) {
                    // Exit application
                    Student.ExitStudentApplication();
                }
            } while (userChoice != 5);
        }   
    }
}
